importo librerias

In [27]:
# Importar las bibliotecas necesarias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

cargo dataset

In [28]:
df_hechos = pd.read_excel(r'D:\projectos\programacion\henrry\bootcamp\proyecto_individuales\2\Proyecto_Individual_N-2_kalchichen_lucas\dataset\Fuente de Datos\homicidios.xlsx', sheet_name='HECHOS')
df_hechos

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,Altura,Cruce,Dirección Normalizada,COMUNA,XY (CABA),pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,NaN,"FERNANDEZ DE LA CRUZ, F., GRAL. AV.","PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...",8,Point (98896.78238426 93532.43437792),-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,...,NaN,DE LOS CORRALES AV.,"PAZ, GRAL. AV. y DE LOS CORRALES AV.",9,Point (95832.05571093 95505.41641999),-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,AV ENTRE RIOS 2034,AVENIDA,...,2034.0,NaN,ENTRE RIOS AV. 2034,1,Point (106684.29090040 99706.57687843),-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,...,NaN,"VILLEGAS, CONRADO, GRAL.","LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.",8,Point (99840.65224780 94269.16534422),-58.46503904,-34.68092974,MOTO-SD,MOTO,SD
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,...,NaN,"SAENZ PE?A, LUIS, PRES.","SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.",1,Point (106980.32827929 100752.16915795),-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,2021-12-13,2021,12,13,17:10:00,17,AV. RIESTRA Y MOM,AVENIDA,...,NaN,MOM,RIESTRA AV. y MOM,7,Point (102728.60090138 98186.24929177),-58.43353773,-34.64561636,MOTO-AUTO,MOTO,AUTO
692,2021-0094,1,2021-12-20,2021,12,20,01:10:00,1,AU DELLEPIANE Y LACARRA,AUTOPISTA,...,NaN,LACARRA AV.,"DELLEPIANE, LUIS, TTE. GRAL. y LACARRA AV.",9,Point (99624.29795829 97569.69801131),-58.46739825,-34.65117757,MOTO-AUTO,MOTO,AUTO
693,2021-0095,1,2021-12-30,2021,12,30,00:43:00,0,AV. GAONA Y TERRADA,AVENIDA,...,NaN,TERRADA,GAONA AV. y TERRADA,11,Point (99116.45492358 101045.23284826),-58.47293407,-34.61984745,MOTO-CARGAS,MOTO,CARGAS
694,2021-0096,1,2021-12-15,2021,12,15,10:30:00,10,AV. EVA PERON 4071,AVENIDA,...,4071.0,NaN,"PERON, EVA AV. 4071",9,Point (99324.54463985 97676.26932409),-58.47066794,-34.65021673,AUTO-CARGAS,AUTO,CARGAS
695,2021-0097,1,2021-11-18,2021,11,18,06:10:00,6,PADRE CARLOS MUJICA 709,CALLE,...,709.0,NaN,PADRE CARLOS MUGICA 709,1,Point (107664.16647795 104708.63962087),-58.37976155,-34.58679619,BICICLETA-AUTO,BICICLETA,AUTO

Visualizar los valores nulos

In [29]:

table_hechos = []
table_victimas = []
table_hechos.append(pd.DataFrame({ 'Nulos': df_hechos.isnull().sum()}))


#imprimir tablas 
for row in table_hechos:
    display(row)

                       Nulos
ID                         0
N_VICTIMAS                 0
FECHA                      0
AAAA                       0
MM                         0
DD                         0
HORA                       0
HH                         0
LUGAR_DEL_HECHO            0
TIPO_DE_CALLE              0
Calle                      1
Altura                   567
Cruce                    171
Dirección Normalizada      8
COMUNA                     0
XY (CABA)                  0
pos x                      0
pos y                      0
PARTICIPANTES              0
VICTIMA                    0
ACUSADO                    0

Descartaremos columnas inutiles 
 * **Altura** presenta un 80 porciento de valores nulos por lo tanto sera descartada
 * **XY(caba)** se descarta por que usaremos latitud y longuitud geografica
 * **Participantes** se descarta por ser una concatenacion de Victimas y Acusado
 * **Año**, **Mes**, **Dia** se descartan por poseer la columna fecha
 * **HORA** se descarta por poseer la columna HH de franja horaria

In [30]:
columnas = [ 'Altura', 'Dirección Normalizada', 'Calle', 'Cruce',
            'AAAA', 'MM', 'DD', 'HORA', 'XY (CABA)', 'PARTICIPANTES']

df_hechos.drop(columns=columnas, inplace=True)

In [31]:
df_hechos.head()

,ID,N_VICTIMAS,FECHA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,COMUNA,pos x,pos y,VICTIMA,ACUSADO
0,2016-0001,1,2016-01-01,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,8,-58.47533969,-34.68757022,MOTO,AUTO
1,2016-0002,1,2016-01-02,1,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,9,-58.50877521,-34.66977709,AUTO,PASAJEROS
2,2016-0003,1,2016-01-03,7,AV ENTRE RIOS 2034,AVENIDA,1,-58.39040293,-34.63189362,MOTO,AUTO
3,2016-0004,1,2016-01-10,0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,8,-58.46503904,-34.68092974,MOTO,SD
4,2016-0005,1,2016-01-21,5,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,1,-58.38718297,-34.62246630,MOTO,PASAJEROS

DETECCION Y TRATAMIENTO DE NULOS

Normalizacion de Datos

In [32]:
#fechas 
df_hechos['FECHA']

0     2016-01-01
1     2016-01-02
2     2016-01-03
3     2016-01-10
4     2016-01-21
         ...
691   2021-12-13
692   2021-12-20
693   2021-12-30
694   2021-12-15
695   2021-11-18
Name: FECHA, Length: 696, dtype: datetime64[ns]

In [8]:
#hora
df_hechos['HH']

0       4
1       1
2       7
3       0
4       5
       ..
691    17
692     1
693     0
694    10
695     6
Name: HH, Length: 696, dtype: object

In [33]:

# Reemplazar 'sd' por NaN en la columna 'HH'
df_hechos['HH'].replace('sd', np.nan, inplace=True)

# Convertir la columna a valores numéricos enteros
df_hechos['HH'] = pd.to_numeric(df_hechos['HH'], errors='coerce').astype('Int64')

C:\Users\lucas\AppData\Local\Temp\ipykernel_15740\1568583278.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_hechos['HH'].replace('sd', np.nan, inplace=True)

In [34]:
#texto
df_hechos['LUGAR_DEL_HECHO']

0      AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ
1              AV GRAL PAZ  Y AV DE LOS CORRALES
2                             AV ENTRE RIOS 2034
3          AV LARRAZABAL Y GRAL VILLEGAS CONRADO
4      AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA
                         ...
691                            AV. RIESTRA Y MOM
692                      AU DELLEPIANE Y LACARRA
693                          AV. GAONA Y TERRADA
694                           AV. EVA PERON 4071
695                      PADRE CARLOS MUJICA 709
Name: LUGAR_DEL_HECHO, Length: 696, dtype: object

In [35]:
df_hechos['TIPO_DE_CALLE']

0        AVENIDA
1       GRAL PAZ
2        AVENIDA
3        AVENIDA
4        AVENIDA
         ...
691      AVENIDA
692    AUTOPISTA
693      AVENIDA
694      AVENIDA
695        CALLE
Name: TIPO_DE_CALLE, Length: 696, dtype: object

In [36]:
df_hechos['VICTIMA']

0           MOTO
1           AUTO
2           MOTO
3           MOTO
4           MOTO
         ...
691         MOTO
692         MOTO
693         MOTO
694         AUTO
695    BICICLETA
Name: VICTIMA, Length: 696, dtype: object

In [37]:
df_hechos['ACUSADO']

0           AUTO
1      PASAJEROS
2           AUTO
3             SD
4      PASAJEROS
         ...
691         AUTO
692         AUTO
693       CARGAS
694       CARGAS
695         AUTO
Name: ACUSADO, Length: 696, dtype: object

In [38]:

# Lista de columnas tipo texto
cols = ['LUGAR_DEL_HECHO', 'TIPO_DE_CALLE', 'VICTIMA', 'ACUSADO']

# Aplicar cambios a las columnas seleccionadas
for col in cols:
    df_hechos[col] = df_hechos[col].str.strip()

In [39]:
#comuna
df_hechos['COMUNA'].unique()
#comuna va del 1 al 15 porque son las 15 comunas de la CABA los 0 seran los nulos selos remplasa Nan numpy

array([ 8,  9,  1, 11, 15,  4,  7, 12,  3, 13, 14, 10,  6,  2,  5,  0],
      dtype=int64)

In [40]:

df_hechos['COMUNA'].replace(0, np.nan, inplace=True)
df_hechos['COMUNA']

C:\Users\lucas\AppData\Local\Temp\ipykernel_15740\3782672164.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_hechos['COMUNA'].replace(0, np.nan, inplace=True)

0       8.0
1       9.0
2       1.0
3       8.0
4       1.0
       ...
691     7.0
692     9.0
693    11.0
694     9.0
695     1.0
Name: COMUNA, Length: 696, dtype: float64

Renombro Colunmbas

In [41]:
Actuales = df_hechos.columns
Nuevas = ['id_hecho', 'cantidad_victimas', 'fecha', 'hora', 'lugar_del_hecho', 
       'tipo_de_calle', 'comuna', 'longitud', 'latitud', 'vehiculo_victima', 'vehiculo_acusado']

columnas = {Actuales: Nuevas for (Actuales, Nuevas) in zip(Actuales, Nuevas)}
df_hechos.rename(columns=columnas, inplace=True)

In [42]:
df_hechos

,id_hecho,cantidad_victimas,fecha,hora,lugar_del_hecho,tipo_de_calle,comuna,longitud,latitud,vehiculo_victima,vehiculo_acusado
0,2016-0001,1,2016-01-01,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,8.0,-58.47533969,-34.68757022,MOTO,AUTO
1,2016-0002,1,2016-01-02,1,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,9.0,-58.50877521,-34.66977709,AUTO,PASAJEROS
2,2016-0003,1,2016-01-03,7,AV ENTRE RIOS 2034,AVENIDA,1.0,-58.39040293,-34.63189362,MOTO,AUTO
3,2016-0004,1,2016-01-10,0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,8.0,-58.46503904,-34.68092974,MOTO,SD
4,2016-0005,1,2016-01-21,5,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,1.0,-58.38718297,-34.62246630,MOTO,PASAJEROS
...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,2021-12-13,17,AV. RIESTRA Y MOM,AVENIDA,7.0,-58.43353773,-34.64561636,MOTO,AUTO
692,2021-0094,1,2021-12-20,1,AU DELLEPIANE Y LACARRA,AUTOPISTA,9.0,-58.46739825,-34.65117757,MOTO,AUTO
693,2021-0095,1,2021-12-30,0,AV. GAONA Y TERRADA,AVENIDA,11.0,-58.47293407,-34.61984745,MOTO,CARGAS
694,2021-0096,1,2021-12-15,10,AV. EVA PERON 4071,AVENIDA,9.0,-58.47066794,-34.65021673,AUTO,CARGAS
695,2021-0097,1,2021-11-18,6,PADRE CARLOS MUJICA 709,CALLE,1.0,-58.37976155,-34.58679619,BICICLETA,AUTO

Guardo dataset limpios

In [43]:
# Los archivos se almacenan en local 
df_hechos.to_csv(r'D:\projectos\programacion\henrry\bootcamp\proyecto_individuales\2\Proyecto_Individual_N-2_kalchichen_lucas\dataset\ETL_datasets\hechos_clean.csv', index=False)
#df_hechos.to_json(r'D:\projectos\programacion\henrry\bootcamp\proyecto_individuales\2\Proyecto_Individual_N-2_kalchichen_lucas\dataset\ETL_datasets\hechos_clean.json', orient='records', lines=True)
#df_hechos.to_parquet(r'D:\projectos\programacion\henrry\bootcamp\proyecto_individuales\2\Proyecto_Individual_N-2_kalchichen_lucas\dataset\ETL_datasets\hechos_clean.parquet', index=False)